name: Inga analysis

on:
  pull_request:

jobs:
  inga-analysis:

    runs-on: ubuntu-latest
    container: ghcr.io/seachicken/inga:latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: gh pr view --json url --json number --json baseRefName --json commits --json comments
    - run: inga --exlclude "*.test.tsx, *.spec.tsx" --github-token ${{ secrets.GITHUB_TOKEN }}
