name: Inga analysis

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  inga-analysis:

    runs-on: ubuntu-latest
    container: ghcr.io/seachicken/inga:latest

    steps:
    - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: npm install -g yarn
    - run: yarn
    - run: /inga/roswell/inga.ros "$(pwd)/" master
    - run: yarn build-storybook
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./storybook-static
