name: Inga analysis

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  inga-analysis:

    runs-on: ubuntu-latest
    container: ghcr.io/seachicken/inga:latest

    steps:
    - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: inga --exlclude "*.test.tsx, *.spec.tsx" --github-token ${{ secrets.GITHUB_TOKEN }}
