name: Inga analysis

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  inga-analysis:

    runs-on: ubuntu-latest
    container: ghcr.io/seachicken/inga:latest

    steps:
    - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
    - run: gh pr view
    - run: git branch --track master origin/master
    - run: /inga/roswell/inga.ros --project-path "$(pwd)/" --sha-a master --exlclude "*.test.tsx, *.spec.tsx"
